import html from '@shikijs/langs/html';
import githubDark from '@shikijs/themes/github-dark';
import githubLight from '@shikijs/themes/github-light';
import { createHighlighterCore } from 'shiki/core';
import { createJavaScriptRegexEngine } from 'shiki/engine/javascript';

/**
 * A highlighted fragment rendered inside the dynamic code sample.
 */
type HighlightedToken = {
	/**
	 * The original source text.
	 */
	content: string;

	/**
	 * Theme-aware inline styles generated by Shiki.
	 */
	htmlStyle?: string | Record<string, string>;
};

const highlighterPromise = createHighlighterCore({
	engine: createJavaScriptRegexEngine(),
	langs: [html],
	themes: [githubLight, githubDark],
});

const highlightCode = async (code: string): Promise<HighlightedToken[][]> => {
	const highlighter = await highlighterPromise;

	return highlighter.codeToTokens(code, {
		defaultColor: false,
		lang: 'html',
		themes: {
			dark: 'github-dark',
			light: 'github-light',
		},
	}).tokens;
};

export { highlightCode };
export type { HighlightedToken };
