name: Playground

on:
  push:
    branches: [master]
    paths:
      - playground/**
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build playground
        run: pnpm build:playground

      - name: Publish to GH pages
        uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a # v4.2.5
        with:
          branch: gh-pages
          folder: playground-bundle
