name: Playground

on:
  push:
    branches: [master]
    paths:
      - playground/**
  # workflow_dispatch: {}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build playground
        run: pnpm run build:playground

      - name: Publish to GH pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: playground-bundle
